server:
  port: 8087

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:appdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  application:
    name: transaction-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}